version: '3'

services:

  connector-ravi:
    build: 
      context: ./../micro-app
      dockerfile: ./../micro-app/connector-ravi.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1